USE Projekt;
DELETE FROM booking_payments;
DELETE FROM companies;
DELETE FROM conference_prices;
DELETE FROM individual_clients;
DELETE FROM workshop_enrollments;
DELETE FROM day_enrollments;
DELETE FROM attendees;
DELETE FROM people;
DELETE FROM workshop_bookings;
DELETE FROM day_bookings;
DELETE FROM workshop_interests;
DELETE FROM bookings;
DELETE FROM clients;
DELETE FROM workshops;
DELETE FROM conference_days;
DELETE FROM conferences;
DBCC CHECKIDENT(conferences, RESEED, 0);

INSERT INTO conferences VALUES ('Akademickie spotkanie programistyczne', 'Warszawa', 'Krótka', '02-495', '2', 0.75);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie programistyczne', 'Warszawa', 'Krótka', '02-495', '19', 0.65);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie informatyków', 'Lublin', 'Długa', '20-410', '36', 0.75);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje programistów', 'Lublin', 'Armii Krajowej', '20-410', '47', 0.0);
INSERT INTO conferences VALUES ('Studenckie warsztaty informatyczne', 'Wrocław', 'Długa', '52-119', '45', 0.8);
INSERT INTO conferences VALUES ('Ademickie zebranie programistów', 'Warszawa', 'Dębowa', '02-495', '0', 0.95);
INSERT INTO conferences VALUES ('Akademickie konferencje informatyków', 'Katowice', 'Słowackiego', '40-236', '28', 0.55);
INSERT INTO conferences VALUES ('Powszechne konferencje informatyków', 'Wrocław', 'Krótka', '52-119', '30', 0.95);
INSERT INTO conferences VALUES ('Akademickie konferencje kół naukowych', 'Kielce', 'Długa', '25-511', '48', 0.5);
INSERT INTO conferences VALUES ('Studenckie warsztaty programistyczne', 'Wrocław', 'Krótka', '52-119', '13', 0.25);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje miłośników programowania', 'Warszawa', 'Słowackiego', '02-495', '2', 0.25);
INSERT INTO conferences VALUES ('Studenckie forum programistyczne', 'Lublin', 'Królewska', '20-410', '15', 0.6);
INSERT INTO conferences VALUES ('Powszechne konferencje programistyczne', 'Kielce', 'Słowackiego', '25-511', '47', 0.4);
INSERT INTO conferences VALUES ('Studenckie warsztaty miłośników programowania', 'Katowice', 'Dębowa', '40-236', '26', 0.35);
INSERT INTO conferences VALUES ('Studenckie forum miłośników programowania', 'Rzeszów', 'Królewska', '35-030', '14', 0.7);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie kół naukowych', 'Katowice', 'Słowackiego', '40-236', '8', 0.05);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie programistów', 'Stalowa Wola', 'Królewska', '37-450', '49', 1.0);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie programistów', 'Rzeszów', 'Wojska Polskiego', '35-030', '28', 0.65);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje informatyków', 'Lublin', 'Lipowa', '20-410', '22', 0.4);
INSERT INTO conferences VALUES ('Powszechne konferencje programistów', 'Szczecin', 'Słowackiego', '71-627', '48', 0.6);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie programistyczne', 'Stalowa Wola', 'Dębowa', '37-450', '1', 0.55);
INSERT INTO conferences VALUES ('Studenckie forum kół naukowych', 'Wrocław', 'Krótka', '52-119', '44', 0.75);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie programistów', 'Poznań', 'Królewska', '61-740', '32', 0.35);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje miłośników programowania', 'Warszawa', 'Mickiewicza', '02-495', '2', 0.0);
INSERT INTO conferences VALUES ('Ademickie zebranie informatyczne', 'Warszawa', 'Armii Krajowej', '02-495', '15', 0.4);
INSERT INTO conferences VALUES ('Akademickie spotkanie informatyczne', 'Kielce', 'Krótka', '25-511', '34', 0.8);
INSERT INTO conferences VALUES ('Akademickie konferencje informatyczne', 'Stalowa Wola', 'Lipowa', '37-450', '37', 0.75);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie informatyczne', 'Katowice', 'Wojska Polskiego', '40-236', '8', 0.5);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie kół naukowych', 'Poznań', 'Długa', '61-740', '41', 0.45);
INSERT INTO conferences VALUES ('Powszechne konferencje kół naukowych', 'Rzeszów', 'Wojska Polskiego', '35-030', '36', 0.25);
INSERT INTO conferences VALUES ('Powszechne konferencje programistyczne', 'Kraków', 'Krótka', '30-055', '18', 0.3);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie informatyczne', 'Rzeszów', 'Krótka', '35-030', '49', 0.85);
INSERT INTO conferences VALUES ('Akademickie spotkanie programistów', 'Poznań', 'Długa', '61-740', '39', 0.7);
INSERT INTO conferences VALUES ('Studenckie forum kół naukowych', 'Stalowa Wola', 'Dębowa', '37-450', '20', 1.0);
INSERT INTO conferences VALUES ('Akademickie konferencje informatyków', 'Rzeszów', 'Mickiewicza', '35-030', '34', 0.75);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje kół naukowych', 'Kraków', 'Lipowa', '30-055', '25', 0.85);
INSERT INTO conferences VALUES ('Studencki festiwal informatyków', 'Katowice', '3 Maja', '40-236', '33', 0.65);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie informatyków', 'Lublin', 'Mickiewicza', '20-410', '30', 0.4);
INSERT INTO conferences VALUES ('Studenckie warsztaty informatyczne', 'Stalowa Wola', 'Długa', '37-450', '28', 0.55);
INSERT INTO conferences VALUES ('Studencki festiwal programistyczne', 'Lublin', 'Długa', '20-410', '16', 0.95);
INSERT INTO conferences VALUES ('Akademickie spotkanie informatyków', 'Stalowa Wola', 'Krótka', '37-450', '24', 0.05);
INSERT INTO conferences VALUES ('Akademickie spotkanie kół naukowych', 'Katowice', 'Długa', '40-236', '8', 0.35);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie miłośników programowania', 'Kielce', 'Słowackiego', '25-511', '40', 0.75);
INSERT INTO conferences VALUES ('Studenckie forum programistyczne', 'Wrocław', 'Wojska Polskiego', '52-119', '18', 0.05);
INSERT INTO conferences VALUES ('Studenckie warsztaty informatyków', 'Lublin', 'Mickiewicza', '20-410', '3', 0.25);
INSERT INTO conferences VALUES ('Akademickie spotkanie informatyczne', 'Poznań', 'Mickiewicza', '61-740', '7', 0.1);
INSERT INTO conferences VALUES ('Studenckie warsztaty programistów', 'Kraków', 'Krótka', '30-055', '7', 0.3);
INSERT INTO conferences VALUES ('Akademickie konferencje informatyczne', 'Szczecin', 'Słowackiego', '71-627', '40', 0.7);
INSERT INTO conferences VALUES ('Powszechne konferencje informatyków', 'Poznań', 'Armii Krajowej', '61-740', '29', 0.3);
INSERT INTO conferences VALUES ('Powszechne konferencje miłośników programowania', 'Rzeszów', 'Królewska', '35-030', '33', 0.75);
INSERT INTO conferences VALUES ('Studenckie forum informatyków', 'Lublin', 'Krótka', '20-410', '13', 0.85);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie programistyczne', 'Lublin', 'Królewska', '20-410', '49', 0.75);
INSERT INTO conferences VALUES ('Studenckie warsztaty programistyczne', 'Rzeszów', '3 Maja', '35-030', '47', 0.2);
INSERT INTO conferences VALUES ('Akademickie konferencje informatyków', 'Wrocław', 'Armii Krajowej', '52-119', '41', 0.45);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie informatyczne', 'Kielce', '3 Maja', '25-511', '10', 0.9);
INSERT INTO conferences VALUES ('Międzyuczelniane forum informatyków', 'Wrocław', 'Armii Krajowej', '52-119', '35', 0.85);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie miłośników programowania', 'Szczecin', 'Długa', '71-627', '9', 0.6);
INSERT INTO conferences VALUES ('Międzyuczelniane forum miłośników programowania', 'Warszawa', 'Armii Krajowej', '02-495', '40', 0.7);
INSERT INTO conferences VALUES ('Ademickie zebranie programistów', 'Szczecin', '3 Maja', '71-627', '38', 0.25);
INSERT INTO conferences VALUES ('Studencki festiwal kół naukowych', 'Poznań', 'Krótka', '61-740', '30', 0.15);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie miłośników programowania', 'Kielce', 'Mickiewicza', '25-511', '19', 1.0);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie programistyczne', 'Lublin', '3 Maja', '20-410', '5', 0.3);
INSERT INTO conferences VALUES ('Międzyuczelniane forum informatyczne', 'Stalowa Wola', '3 Maja', '37-450', '32', 0.3);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie kół naukowych', 'Kielce', 'Mickiewicza', '25-511', '24', 0.45);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje kół naukowych', 'Wrocław', '3 Maja', '52-119', '49', 0.95);
INSERT INTO conferences VALUES ('Studenckie warsztaty informatyczne', 'Stalowa Wola', 'Krótka', '37-450', '17', 0.2);
INSERT INTO conferences VALUES ('Międzyuczelniane forum programistów', 'Poznań', 'Wojska Polskiego', '61-740', '33', 0.1);
INSERT INTO conferences VALUES ('Międzyuczelniane forum informatyczne', 'Stalowa Wola', 'Armii Krajowej', '37-450', '32', 0.0);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie informatyczne', 'Poznań', 'Armii Krajowej', '61-740', '42', 0.65);
INSERT INTO conferences VALUES ('Międzyuczelniane forum miłośników programowania', 'Kielce', 'Mickiewicza', '25-511', '9', 0.95);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie informatyczne', 'Lublin', 'Lipowa', '20-410', '33', 0.25);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje informatyków', 'Rzeszów', 'Mickiewicza', '35-030', '36', 0.0);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje kół naukowych', 'Stalowa Wola', 'Długa', '37-450', '23', 1.0);
INSERT INTO conferences VALUES ('Studenckie zgromadzenie programistów', 'Warszawa', 'Dębowa', '02-495', '6', 0.6);
INSERT INTO conferences VALUES ('Studencki festiwal programistyczne', 'Wrocław', 'Słowackiego', '52-119', '21', 0.3);
INSERT INTO conferences VALUES ('Akademickie spotkanie programistyczne', 'Stalowa Wola', 'Słowackiego', '37-450', '29', 0.95);
INSERT INTO conferences VALUES ('Studenckie warsztaty miłośników programowania', 'Poznań', '3 Maja', '61-740', '49', 0.35);
INSERT INTO conferences VALUES ('Ogólnopolskie konferencje programistyczne', 'Wrocław', 'Lipowa', '52-119', '48', 0.2);
INSERT INTO conferences VALUES ('Ogólnopolskie spotkanie informatyczne', 'Szczecin', '3 Maja', '71-627', '11', 1.0);
INSERT INTO conferences VALUES ('Powszechne konferencje programistyczne', 'Poznań', 'Dębowa', '61-740', '49', 0.25);

